IMAGE_NAME = "bento/debian-12"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
	debian.vm.network "forwarded_port", guest: 22, host: 2206, host_ip: "127.0.0.1"
	debian.vm.network "forwarded_port", guest: 80, host: 8006, host_ip: "127.0.0.1"
        debian.vm.hostname = "debian"
	debian.vm.provision "shell", inline: "sudo apt-get update", run: "always"
	debian.vm.provision "shell", inline: "sudo apt install -y apache2", run: "always"
	debian.vm.provision "shell", inline: "sudo apt install -y mariadb-server", run: "always"
    end

    config.vm.provision "file", source: "id_ed25519.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys

    SHELL

#     config.vm.provision "shell", path: "install-zabbix-agent2.sh"

#     config.vm.provision "shell", path: "configure-zabbix-agent2.sh"

end